name: BrainPower
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - anyio=3.5.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - asttokens=2.0.5
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.3
  - codecarbon=2.1.4
  - colorama=0.4.6
  - colorlog=5.0.1
  - colormap=1.0.1
  - comm=0.1.2
  - conda=23.1.0
  - conda-content-trust=0.1.3
  - conda-package-handling=1.9.0
  - contourpy=1.0.5
  - cryptography=38.0.1
  - cycler=0.11.0
  - dash=2.8.1
  - dash-bootstrap-components=1.3.1
  - dash-core-components=2.0.0
  - dash-html-components=2.0.0
  - dash-table=5.0.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - easydev=0.12.0
  - entrypoints=0.4
  - executing=0.8.3
  - fftw=3.3.9
  - fire=0.4.0
  - flask=2.2.3
  - flask-compress=1.13
  - flit-core=3.6.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - fuzzywuzzy=0.18.0
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=68.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - ipykernel=6.19.2
  - ipython=8.7.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - itsdangerous=2.1.2
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter=1.0.0
  - jupyter_client=7.4.8
  - jupyter_console=6.4.4
  - jupyter_core=5.1.1
  - jupyter_server=1.23.4
  - jupyterlab=3.5.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.16.5
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.4
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libllvm12=12.0.0
  - libopenblas=0.3.21
  - libpng=1.6.37
  - libpq=12.9
  - libsodium=1.0.18
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxgboost=1.7.3
  - libxml2=2.9.14
  - libxslt=1.1.35
  - llvm-openmp=14.0.6
  - lxml=4.9.1
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - munkres=1.1.4
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - nose=1.3.7
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1t
  - packaging=22.0
  - pandas=1.5.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - platformdirs=2.5.2
  - plotly=5.13.0
  - pluggy=1.0.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - py-xgboost=1.7.3
  - pycosat=0.6.4
  - pycparser=2.21
  - pygments=2.11.2
  - pynvml=11.5.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-levenshtein=0.12.2
  - python.app=3
  - pytz=2022.7
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.3.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.1
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - scikit-learn=1.2.0
  - scipy=1.9.3
  - seaborn=0.12.2
  - send2trash=1.8.0
  - setuptools=65.5.0
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - stack_data=0.2.0
  - tenacity=8.2.1
  - termcolor=2.2.0
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.13
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.2.3
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xgboost=1.7.3
  - xz=5.2.8
  - zeromq=4.3.4
  - zipp=3.14.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - pyqt5-sip==12.11.0
      - rdkit==2022.9.4
